camp/urls.py
from django.urls import path 
from .views import  Current
from . import views
from django.views.generic import TemplateView
from .api_view import camplist , nomlist,apivote , NominatedUpdate ,AddVoterId,currentcamp#,voteridcheck
app_name = 'camp'

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),

    path('valid/',views.validcamp,name='validcamp'),
    path('vote/<slug:slug>',views.vote,name='vote'),
    path('current/',Current.as_view(),name='current'),


    #camp api 
    path('api/camplist',camplist,name='campain_list_api'),
    path('api/current' , currentcamp , name='current_api'),
    #nominated api
    path('api/nomlist',nomlist,name='nom_list_api'),
    path('api/vote/<int:id>' , apivote , name='api_vote'),
    path('api/nomupdate/<int:pk>' , NominatedUpdate.as_view() , name = 'nom_update'),
    #voterid api
    path('api/addvoterid' , AddVoterId.as_view() , name='add_voterid'),
    # path('api/votercheck/<int:id>',voteridcheck,name='voter_id_check'),

]   

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static 
from rest_framework_swagger.views import get_swagger_view
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView

schema_view = get_swagger_view(title='Pastebin API')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('camp.urls',namespace='home')),


    path('summernote/',include('django_summernote.urls')),
    path('api-auth/',include('rest_framework.urls')),
    path('api_schema/', get_schema_view(title='API Schema',description='Guide for the REST API' ), name='api_schema'),
    path('docs/', TemplateView.as_view(template_name='docs.html', extra_context={'schema_url':'api_schema'}), name='swagger-ui'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camp/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
camp_choices=(
    ('S','Single'),
    ('M','Multiple'),

)
#########################################

class Campaign(models.Model):
    name = models.CharField(max_length=100)
    details = models.TextField(max_length=2000)
    image = models.ImageField(upload_to='campimges/',null=True,blank = True)
    starttime = models.DateTimeField(default=timezone.now)
    endtime = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(null=True  , blank=True,unique=True)
    camptype = models.CharField(choices=camp_choices,max_length=20,default='Single')
    current = models.BooleanField(default=False)

    def __str__(self):
        return self.name 

    def save (self ,*args,**kwargs):
        if not self.slug :
            self.slug = slugify(self.name)
        super(Campaign,self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('campaign:campaign_detail',kwargs={'slug' : self.slug})  
      
    

     
#########################################      

class VoterId(models.Model):
    campaign = models.ForeignKey(Campaign , related_name="campaign_voterid" , on_delete = models.CASCADE)
    voterid = models.IntegerField(default=0,unique=True)
    def __str__(self):
        return str(self.campaign)
    


#########################################

class Nominated(models.Model):
    campaign = models.ForeignKey(Campaign , related_name="campaign_nominated" , on_delete = models.CASCADE)
    name = models.CharField(max_length=100)
    details = models.TextField(max_length=2000)
    image = models.ImageField(upload_to='nominatedimage/',null=True,blank = True)
    votecount = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

camp/forms.py
from django import forms
from camp.models import Campaign, Nominated



class Currentform(forms.ModelForm):
    class Meta :
        model = Campaign
        fields = ['current']

camp/views.py
from django.shortcuts import render
from django.views.generic.edit import FormMixin
# Create your views here.

from django.views.generic import ListView 
from camp.forms import Currentform
from camp.models import Campaign, Nominated

#########################################

def validcamp(request):
    valid =Campaign.objects.filter(current = True)
    return render(request,'voting/validcamp.html',{'valid':valid})

########################################
def vote(request,slug) :
    campaign= Campaign.objects.filter(slug=slug)    
    for campaign in campaign : 
        nomi = Nominated.objects.filter(campaign= campaign)
        return render(request,'voting/vote.html',{'nomi':nomi})
    
########################################

class Current(ListView,FormMixin) :
    model = Campaign
    form_class = Currentform
    template_name = 'voting/current.html'

    current = False
    def form_valid(self, form):
        self.current = True
        return super().form_valid(form)
########################################

class voting (ListView) :
    model = Nominated

    def get_queryset(self):
        id = self.id
        object
        return super().get_queryset()

camp/templates/docs.html
<!DOCTYPE html>
<html>
  <head>
    <title>School Service Documentation</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout"
      })
    </script>
  </body>
</html>

camp/templates/home.html
<h3><a href="{%url 'home:current'%}">Current Campaings</a></h3>
<h3><a href="{%url 'home:validcamp'%}">Valid Campaings</a></h3>

camp/templates/voting/current.html
{% load bootstrap4 %}
{% for campaign in object_list %}

<h1>{{campaign.name}}</h1>
<form action="" method="post" , class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {%buttons%}
        <button type="submit" class="btn btn-primary">Edit This Campaign</button>
    {% endbuttons%}
</form>
{% endfor %}

camp/templates/voting/validcamp.html
{% for campaign in valid %}

<h1><a href="{%url 'home:vote' campaign.slug%}">{{campaign.name}}</a></h1>
<h4>{{campaign.details|safe|truncatewords:2}}</h4>
{% endfor %}

camp/templates/voting/vote.html
{% for nominated in nomi %}

<h1>{{nominated.name}}</h1>
<h4>{{nominated.details|safe}}</h4>
{% endfor %}

templates/base.html
{% block body %}

{% endblock body %}
 